name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "938ea5d175f6fd5a66aff642801bb03571b429b9c254dc7a996e07a23fdc58ee"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
