name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ab2696bb32db6e811e3280686b226331d8e56ead49997fc4821ce83ef459c8b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
