name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e8b6cbe86c60be6e9e2e09f5a9bfb91f0be764e30bc2f3b8342bca60287039a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
