name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb4ed16ebc9120ca093632710541fc72f78c8109ca817923c8d197969c2ca26"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
