name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a131ae72506d279118ff020bf59bca3ee2a505f928db50332c4b586bb5d4ca5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
