name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f514dbb950059f6b14496e50811389ffd3d7a882d4c60afd1647ebb53e7edc0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
