name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7173fa0aa86617dfc4d65a1e12d664e80bdcab455ea7e9d3ea094567f2a78194"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
