name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b355187d25cdf8e6388aa8ee992d5d3e483ac09a329dea9d7cf41af02cc99dfe"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
