name = "Family"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0ea323f4a6d57c1637059bb4762cf8bf913b03d9440516b4394219b69a69fed"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
